name: Continuous integration with GitHub
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - name: Give execute permission to gradlew
        run: chmod +x ./gradlew
      - name: Clean project
        run: ./gradlew clean
      - name: Run all tests
        run: ./gradlew testClasses
      - name: Create .jar and install
        run: ./gradlew bootJar
